[package]
name = "rsteam"
version = "0.0.4"
edition = "2021"
authors = ["Kalle Kankaanpää <kalle.kankaanpaa@protonmail.com>"]
description = "rsteam is a easy to use async wrapper for the steam web api"
license = "MIT"
keywords = ["steam", "api", "wrapper"]
categories = ["api-bindings", "asynchronous", "web-programming::http-client"]
repository = "https://github.com/KnoxZZ/rsteam"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
hyper = { version = "0.14.14", features = ["client", "http1", "tcp", "stream"] }
hyper-tls = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.2"