name: Build and test

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    environment: Steam
    steps:
    - uses: actions/checkout@v4
    - name: Test
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      run: cargo test --verbose