name: Cargo test

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    environment: Steam
    steps:
    - uses: actions/checkout@v4
    - name: Test
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      run: cargo test --verbose