name: Cargo test

on:
  push:
    branches: [master, next]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Run rustfmt and Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: Rustfmt
      run: cargo fmt
    - name: Clippy
      run: cargo clippy
  
  minimal-versions:
    name: Build with direct-minimal-versions flag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Build
      run: cargo build -Zdirect-minimal-versions

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    environment: Steam
    steps:
    - uses: actions/checkout@v4
    - name: Test
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      run: cargo test --verbose